# terraform-pipeline.yml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: '1.0.5'

- task: TerraformTaskV1@0
  displayName: 'Terraform Init'
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    backendServiceArm: 'terraform-backend'

- task: TerraformTaskV1@0
  displayName: 'Terraform Apply Resource Group'
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/modules/resource_group'
    environmentServiceNameAzureRM: 'terraform-env'

- task: TerraformTaskV1@0
  displayName: 'Terraform Apply Virtual Network'
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/modules/virtual_network'
    environmentServiceNameAzureRM: 'terraform-env'